services:
  backend:
    profiles:
      - main
    restart: unless-stopped
    build:
      dockerfile: ./ServerOverflow.Backend/Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - "./vol/stats.json:/app/stats.json:rw"
  frontend:
    profiles:
      - main
    restart: unless-stopped
    build:
      context: ./ServerOverflow.Frontend/
      dockerfile: Dockerfile
  nginx:
    profiles:
      - main
    restart: unless-stopped
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "9000:80"
  snooper:
    profiles:
      - snooper
    restart: unless-stopped
    build:
      dockerfile: ./ServerOverflow.Snooper/Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI}
      PROXY_URL: ${PROXY_URL}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_PASSWORD: ${PROXY_PASSWORD}